spring:
  application:
    name: adx-api
  datasource:
    url: ${ADX_DATASOURCE_URL}
    username: ${ADX_DATASOURCE_USERNAME}
    password: ${ADX_DATASOURCE_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  liquibase:
    change-log: classpath:/db/changelog/master.xml

server:
  port: ${ADX_API_PORT:8080}
  ssl:
    key-store: ${SSL_KEYSTORE_LOCATION}
    key-store-password: ${SSL_KEYSTORE_PASSWORD}
    keyStoreType: PKCS12
    keyAlias: tomcat
