name: Deploy

on:
  push:
    branches:
      - main
jobs:
  publish:
    name: Publish to Github Container Registry (ghcr)
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: 'Checkout'
        uses: actions/checkout@main

      - name: 'Login to ghcr'
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{github.actor}}
          password: ${{secrets.GITHUB_TOKEN}}

      - name: 'Build and push to ghcr'
        run: |
          docker build . --tag ghcr.io/airdex-monitoring/adx-api:latest
          docker push ghcr.io/airdex-monitoring/adx-api:latest

  deploy:
    name: Deploy to production
    needs: publish
    runs-on: [self-hosted]

    steps:
      - name: Login to ghcr
        run: cat ${{ secrets.WORKING_DIRECTORY }}/ghcr_crpat.txt | docker login ghcr.io -u airdex-monitoring --password-stdin

      - name: Pull image from ghcr
        run: docker pull ghcr.io/airdex-monitoring/adx-api:latest

      - name: Deploy docker stack
        working-directory: ${{ secrets.WORKING_DIRECTORY }}/adx-api
        env:
          ADX_DATASOURCE_URL: ${{ secrets.ADX_DATASOURCE_URL }}
          ADX_DATASOURCE_USERNAME: ${{ secrets.ADX_DATASOURCE_USERNAME }}
          ADX_DATASOURCE_PASSWORD: ${{ secrets.ADX_DATASOURCE_PASSWORD }}
        run: |
          docker stack deploy -c docker-compose-apistack.yml --with-registry-auth adx-api
